Geometry Creation of EMB Using Ansys Maxwell â€” Lesson 3 - YouTube
https://www.youtube.com/watch?v=UZ-ZPmIih-M

Transcript:
(00:07) Welcome So, I hope you already viewed the video module reviewing the Ansys Electronic Desktop user interface before continuing on to this video because it helps you understand some of the acronyms being used. So, let's get started! Launch the Ansys Electronics Desktop AEDT Student version. All Maxwell simulations have the same necessary steps needed in order to start a simulation and while AEDT is open launch the Maxwell project on the desktop tab > Maxwell, in that drop down arrow select the Maxwell 3D.
(00:45) A new Maxwell 3D design is added under the project folder. Rename that project as EMB. Now, let's setup a few things to make sure our model geometry creation is easier. Head over to the tools, Options > General Options under 3D modeler, drawing. Make sure that the edit properties for new primitives is checked and under draw tab check and make sure the units are in millimeters.
(01:15) Ok, let's go ahead and draw the model as per the dimensions shown here. Let's go ahead create the core. Use the drawing tools available under the draw tab. Go ahead select draw cylinder. Left mouse click on the origin, expand it in the XY plane and then left mouse click anywhere else and then expand it in the Z plane and left mouse click again to complete drawing of the cylinder.
(01:41) A properties window opens up. Change the radius to 25 and the height to 20. Remember you can always select the already created objects from the history tree in the properties panel. Change the dimensions as required or use the variables. Use ctrl+D to fit in view what you just drawn the whole model geometry in the 3D modeler window.
(02:06) Here is some additional shortcut keys that I find useful. Go ahead create the spacer and the coil in the core. Select draw circle, click on the top center of the core as your center click elsewhere in the plane to create some circle. As before, the properties window appears. Change the radius to 20. Draw another circle and change its radius to 15 and that was renamed as circle2.
(02:39) Select circle1 and hold down the ctrl key and select circle2. Now you have selected both circles. Click on subtract on the draw ribbon. Be sure circle1 is the blank tool and circle2 is the tool in the popup dialogue box. You can select the clone tool objects before operation if you want to keep that tool object and have it remained after the subtraction.
(03:07) Now click ok. Select circle1, right mouse click, Edit > Surface > Thicken Sheet and input -15 millimeters in the popup window. Now the negative sign as we wanted to extend it in the negative Z direction. Hold down the ctrl key and select cylinder1 and circle1 and choose subtract. On that popup window select clone tool objects and click ok.
(03:33) Let's assign some attributes to the core and coil. Double click on cylinder1 and change the name to core. Click on the cell next to the material, select edit and choose steel 1008 material. Choose the color close to steel and change the transparency say to 50%. Double click on circle1 and change the name to coil and change the material to copper and change the color, the transparency.
(04:02) Now, let's create the center hole for the shaft. Select create cylinder, select the origin and draw cylinder and in that popup window change the radius to 4 millimeters and the height to 20 millimeters and click ok. Hold the ctrl key and select core and cylinder1 then choose subtract. In that popup window, click ok.
(04:27) Now to create the brake plate click F for face on the keyboard. You're in face selection mode now. Select the bottom surface of the core, right mouse click > Edit select surface and create object from face. Select the newly created object, right mouse click, Edit > Surface > Thicken sheet and set 4 millimeter as the thickness in that popup window box.
(04:55) Keep the object selected, choose move from the draw ribbon, select the origin and move along the Z axis by holding the Z key on the keyboard, left mouse click to set and release somewhere. When the popup window appears change the Z value to 24 mm + gap. That popup window defines the variable gap. Select unit type as length and value as 0.
(05:25) 3 millimeters and this gap parameter is used for setting up the parametric analysis to see the effect of that airgap in the force as exerted by the electromagnets on that brake plate. So, go ahead rename this object brake plate. Create the holes for the spacer screws. Change the model orientation to top view, select create cylinder and draw cylinder towards the outer edge of the core.
(05:53) In the popup window change the center position as shown, radius 1.5 millimeters and height -15 millimeters. Keep the cylinder selected and from the draw ribbon select duplicate around the axis. In that popup window, select the Z axis, angle 90 degrees and total number of 4, select attach to original object and click ok.
(06:21) Multiselect by holding the ctrl key again and select the core, the brake plate and the 4 cylinder objects. Click subtract and from the draw tab. Be sure the brake plate is the blank part. Click ok. Now we have created the holes for the spacer screws and we're not going to create the holes for the springs.
(06:44) For demonstration purposes this should be good enough. Follow the above steps if you really wants to include the spring holes. We're done with the geometry creation. Save the project using ctrl+S. Now thank you for watching this video as we create the model geometry for the EM brake design for the cargo door actuation application.
(07:09) Continue ahead to the next video where we're going to setup the excitation, the boundary conditions with the parametric analysis gap and see the various results as we vary that gap and see its effect. Visit courses.ansys.com and watch our video modules on all of the Ansys simulation tools as well as related topics.